Pik 4250 add the new list of native blockchain assets as supported
fireblocks/fireblocks-network-link pull request #80
Opened 2023-12-28 06:41 UTC by shakedfb

2023-12-31 09:39 UTC, amirhac approved these changes
LGTM

2024-01-04 14:43 UTC, yanivmo requested changes

2024-01-04 14:43 UTC, yanivmo commented on v2/openapi/fb-provider-api.yaml
> +    CryptocurrencySymbol:
It should be "cryptocurrency code" or something like that.

For example, for USD:
- Name: United States dollar
- Symbol: $
- Currency code: USD

2024-01-04 14:51 UTC, yanivmo commented on v2/openapi/fb-provider-api.yaml
> +    CryptocurrencySymbol:
Since this might introduce a breaking change into the API, let's keep it as it is 😞

2024-01-04 14:51 UTC, yanivmo approved these changes

2024-01-04 14:52 UTC, merged